services:
  dispatcher:
    build: .
    container_name: dispatcher
    ports:
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./test-env/ssl/:/certs/:ro
    environment:
      - LOG_LEVEL=debug

  vitrin1:
    image: ghcr.io/mehdi-behrooz/freiheit-vitrin:latest
    container_name: vitrin1
    environment:
      - MESSAGE="This is vitrin 1 speaking"
    labels:
      - dispatcher.type=http
      - dispatcher.hosts=example1.com

  vitrin2:
    image: ghcr.io/mehdi-behrooz/freiheit-vitrin:latest
    container_name: vitrin2
    environment:
      - MESSAGE="This is vitrin 2 speaking"
    labels:
      - dispatcher.type=http
      - dispatcher.hosts=example2.com
